---
abstract: 'Create a nice formatted table using ASCII characters.'
author:
  - 'Håkon Nessjøen, <lunatic@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-ASCIITable
provides:
  Text::ASCIITable:
    file: lib/Text/ASCIITable.pm
    version: 0.22
  Text::ASCIITable::Wrap:
    file: lib/Text/ASCIITable/Wrap.pm
    version: 0.2
requires:
  Carp: 0
  Encode: 0
  List::Util: 0
  perl: v5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.22
