#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-ASCIITable
version:      0.14
version_from: ASCIITable.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
